### ISSUE TITLE
`gts fix` fails on nodejs-spanner

### ISSUE THREAD

**Issue by JustinBeckwith** [google/ts-style#267]
Today we started to see these errors during `gts fix` in googleapis/nodejs-spanner:

```
> @google-cloud/spanner@2.2.1 fix /Users/beckwith/Code/nodejs-spanner
> gts fix && eslint --fix '**/*.js'

Configuration file(s) do(es) not support C++: /Users/beckwith/Code/nodejs-spanner/.clang-format
Configuration file(s) do(es) not support C++: /Users/beckwith/Code/nodejs-spanner/.clang-format
Configuration file(s) do(es) not support C++: /Users/beckwith/Code/nodejs-spanner/.clang-format
Configuration file(s) do(es) not support C++: /Users/beckwith/Code/nodejs-spanner/.clang-format
Error: clang-format exited with exit code 1.
    at errorFromExitCode (/Users/beckwith/Code/nodejs-spanner/node_modules/clang-format/index.js:16:10)
    at ChildProcess.<anonymous> (/Users/beckwith/Code/nodejs-spanner/node_modules/clang-format/index.js:121:14)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google-cloud/spanner@2.2.1 fix: `gts fix && eslint --fix '**/*.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @google-cloud/spanner@2.2.1 fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beckwith/.npm/_logs/2019-02-15T16_57_38_147Z-debug.log
```

After a bit of a searching around, it looks like `clang-format` has decided that one of our source files looks like `C++`.  
https://github.com/angular/clang-format/issues/58

**Comment by ofrobots** [comment]
This is fixed on master, so I think this can be closed. Let me know if this is a mistake.
